[database]
url = "sqlite:ipfs_registry.db"

#[storage]
#layers = [
  #{ url = "http://localhost:5001" }
#]

#[cors]
#origins = [
  #"https://localhost:9060",
  #"https://localhost:9060",
#]

#[tls]
#cert = "cert.pem"
#key = "key.pem"
