[package]
name = "ipfs-registry"
version = "0.1.0"
edition = "2021"
description = "Signed package registry backed by IPFS"

[workspace]
members = [
  "workspace/client",
  "workspace/core",
  "workspace/server",
]
