[package]
name = "ipfs-registry"
version = "0.1.0"
edition = "2021"
description = "Signed package registry backed by IPFS"

[workspace]
members = [
  "workspace/client",
  "workspace/core",
  "workspace/server",
]

#[patch.crates-io]
 #ipfs-api-backend-hyper= { path = "../../forks/rust-ipfs-api/ipfs-api-backend-hyper" }
