use thiserror::Error;

#[derive(Debug, Error)]
pub enum Error {
    #[error("tarball does not contain a valid NPM package.json")]
    NoNpmPackage,

    /// Error generated by the io module.
    #[error(transparent)]
    Io(#[from] std::io::Error),

    /// Error generated by the JSON library.
    #[error(transparent)]
    Json(#[from] serde_json::Error),
}
